server:
  servlet:
    context-path: /backstage

spring:
  profiles:
    active: '@env@'
  main:
    allow-bean-definition-overriding: true
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.jdbc.Driver
#    druid:
#      filter:
#        wall:
#          config:
#            multi-statement-allow: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08
